### ISSUE TITLE
Indentation not available for `fn-traced` forms

### ISSUE THREAD

**Issue by stumitchell** [day8/re-frame-10x#267] opened 2020-06-09 01:31 UTC
The following code is not indented

```
(re-frame/reg-event-db
 ::let
 (fn-traced [db _]
   (let [a 10
         b (+ a 20)]
     (+ a b)
     db)))

```
![image](https://user-images.githubusercontent.com/738393/84096230-86e02500-aa55-11ea-92a2-bb10f686b0fa.png)

**Comment by danielcompton** [comment] 2020-06-10 01:10
I'm 95% sure that that information isn't available in the macroexpansion, you only get the parsed s-expression data. I think you'd need to use a Clojure formatter to reformat this to something reasonable.

**Comment by mike-thompson-day8** [comment] 2020-06-10 01:24
@danielcompton 
Yes, understood. We created this issue to remind us that the reformatting is not working on this code. Perhaps because it is too simple.  Anyway, more investigation needed. 

Perhaps we should move to use a different (better?) code reformatter. Calva uses [cljfmt](https://github.com/weavejester/cljfmt)

**Comment by danielcompton** [comment] 2020-06-10 01:43
I don't think cljfmt will break the lines for you given the data. I haven't investigated deeply, but possibly something like https://github.com/greglook/cljstyle or https://github.com/nedap/formatting-stack might be able to reform code from data.

**Comment by kimo-k** [comment] 2023-07-10 12:59
"Can't repro with the provided function. Zprint is working as intended on my local build. I checked on both 1.7.0 and 1.6.0.

It is interesting that you'd get this result, since we've been formatting this code with zprint since at least 2018. Zprint won't reproduce the exact linebreaks in your code, but it does format your example reasonably, spreading it over 4 lines.

Closing for now.

**Closed by kimo-k** 2023-07-10 12:59 UTC
Labels: size:medium
