### ISSUE TITLE
Open/close arrows stop working randomly

### ISSUE THREAD

**Issue by mtravers** [day8/re-frame-10x#251] opened 2019-10-09 00:05 UTC
Every so often, for no apparent reason, the open/close widgets in the app-db browser just stop working completely. When this happens, none of them will respond at all (aside from the top-level one -- but any opener on a green background is completely nonfunctional. Same behavior with 0.4.1 0.4.3.

Driving me crazy, because it makes this otherwise extremely valuable tool kind of useless.

**Comment by mike-thompson-day8** [comment] 2019-10-09 00:13
Are you using the latest version?

**Comment by mike-thompson-day8** [comment] 2019-10-09 00:18
This is a duplicate of https://github.com/Day8/re-frame-10x/issues/209 but we thought it was fixed with v0.4.3   (I'm assuming you are using 0.8.x and React 16.8.6)

BTW, I assume you are aware of the workaround:
https://github.com/Day8/re-frame-10x#the-expansion-triangles-in-the-data-browsers-dont-work-any-more-but-they-used-to

**Comment by mtravers** [comment] 2019-10-09 00:58
I'm using Reagent 0.8.1, which is the latest available AFAIK, which brings
in [cljsjs/react "16.3.2-0"].

Wasn't aware of the workaround, thanks for pointing it out (but completely
resetting Chrome isn't something I want to do very often).

**Comment by mike-thompson-day8** [comment] 2019-10-09 01:10
No need for a complete reset, just local storage for your app. 
> While running your app), in Chrome, go to devtools (F12), choose the Application Tab and then select (on the left) `Local Storage` and clear out what's there. Restart your app. Fixed? (Warning this removes your re-frame-10x settings)

**Comment by superstructor** [comment] 2019-10-16 03:19
@mtravers Firstly apologies for this issue. We know its annoying and we want to get this fixed.

Is there any additional information you can provide to help me find reliable reproduction steps ? 

Roughly how frequently do you experience the issue ? 

Does this only occur when using re-frame-10x in an external window or does it also occur as the default internal panel on the right ?

**Comment by mtravers** [comment] 2019-10-16 05:41
Thanks for the reply!

I can't really give reproducible steps, sorry. It happens infrequently, and
I *think* it only happens when using the external window (however, once it
gets in stuck mode the problem appears on the internal panel as well).

**Comment by superstructor** [comment] 2020-03-04 23:09
![Screenshot from 2020-03-05 12-08-49](https://user-images.githubusercontent.com/350450/75931561-25e70500-5eda-11ea-84fc-c67f2e4bf485.png)

**Comment by hipitihop** [comment] 2020-08-20 07:08
I believe the core issue is caused by the re-frame application tab in the browser losing focus. When you switch to another tab in the **same** Chrome window, all 10x interactions stop responding, top tabs and including the expand arrows. When you switch tab back to your re-frame application, 10x catches up and responds to the last interaction.

> **NOTE 1:** Effects all interactions, not just the arrows.

> **NOTE 2:** Only happens when switching tabs within the same Chrome window. General focus change, e.g. if you have another Chrome window open and you switch to that while you re-frame application tab is still the current tab in the other Chrome window, then 10x continues to function as expected.

**Comment by kimo-k** [comment] 2023-07-26 10:21
Closing for now.

Can't reproduce the original bug. @mtravers, please let us know if you're still affected.

Added some documentation for the behavior described above by @hipitihop. This is technically fixable, but the fix seems high-effort and could have browser compatibility & legacy issues. 

More importantly, the concern is out of scope, IMO. If there's a critical use-case for switching tabs in the browser window where your app is running, please let us know. Otherwise, you can always just [use a different window](https://github.com/day8/re-frame-10x/blob/cbd0fde969db2f6feb79070da7e01c84d37d6e0d/README.md?plain=1#L345).

**Closed by kimo-k** 2023-07-26 10:21 UTC
Labels: bug, size:large
