### ISSUE TITLE
Broken Code formatting in Events tab. 

### ISSUE THREAD

**Issue by mike-thompson-day8** [day8/re-frame-10x#270] opened 2020-07-07 22:55 UTC
This change to HTML styles broke the code formatting at the top of the `Events` tab.  
https://github.com/day8/re-frame-10x/commit/40e7e7da18c9cc3b755d0247f5b41a754c4e0a07

After this change, the code shown (at the top of the events tab) never had newlines, and was always string onto one line.

**Comment by Gregg8** [comment] 2020-07-08 02:17
Some background:

There have been three related styling commits this year:
 - [Fix icon rendering differences between some browsers](https://github.com/day8/re-frame-10x/commit/6db8360e02cf21cec5a43f87857bcac3b1b9ffc0)
 - [Fix styling override regressions introduced in 0.4.6](https://github.com/day8/re-frame-10x/commit/6db8360e02cf21cec5a43f87857bcac3b1b9ffc0)
 - [Improve CSS reset styles and fix styling bugs](https://github.com/day8/re-frame-10x/commit/40e7e7da18c9cc3b755d0247f5b41a754c4e0a07) (as mentioned above)

Originally, 10x only really targeted Chrome and this was work to make it display better in other browsers, but specifically MS Edge, which unfortunately is the browser used in Microsoft 365 JS Add-ins.

Icons (which are svg) did not display at all in Edge and so it was determined this was because the reset CSS was not working and so these were the changes made.

As it happens, the third commit caused the unwanted effect of removing all newlines from the displayed event code in the Events tab.

On looking into this, it's the `[:pre]` that is responsible for adding the newlines and the new reset CSS messes with this, so we need to target the styling of that, but making sure nothing else breaks.

**Additional TODO**: Currently, the svg arrows display as a grey button under Edge so need to look into that as well...

![image](https://user-images.githubusercontent.com/3037372/86866705-d5e0af00-c114-11ea-81a3-3305ea2e2b2c.png)

**Comment by Gregg8** [comment] 2020-07-08 05:36
Did a quick fix to get the newlines going again: https://github.com/day8/re-frame-10x/commit/8de832980c7aab9553d07c4443794c02b6636d1e

Need to spend more time to get the right method of resetting the CSS

**Comment by MawiraIke** [comment] 2022-05-17 18:12
Looks like this issue is fixed as of version 1.2.7?
The code in events tab has newlines now and, arrows are working in MS edge.

MS Edge:
![MS Edge arrows](https://user-images.githubusercontent.com/38689046/168881030-edd8d68f-827f-446c-98dc-f2b2fc6745e9.jpg)

Code formating in events tab:
![events-code](https://user-images.githubusercontent.com/38689046/168881281-97947d4a-1261-4527-93ff-34d56de89deb.jpg)

**Comment by superstructor** [comment] 2022-05-17 22:55
@Gregg8 please confirm ?

**Comment by kimo-k** [comment] 2023-07-26 08:48
Appears to be fixed since dad02ff85793119f6ccfeeb9df328cfe91ec6354

**Closed by kimo-k** 2023-07-26 08:48 UTC
Labels: enhancement
