### ISSUE TITLE
Layout interference in Chrome devtools device emulation

### ISSUE THREAD

**Issue by conan** [day8/re-frame-10x#215] opened 2018-08-15 16:26 UTC
When using Chrome's dev tools, if I click the icon to open the device toolbar (the one that pretends you're using a phone, next to the CSS pointy tool) and select iphone 5x, re-frame-10x interferes with the layout - when hidden, it slides out of view but the rest of the layout does not update.  

This might be something to do with my CSS implementation, but I'm exclusively using Bootstrap and I feel like a tool such as this shouldn't interfere with my layout.  When doing a lot of responsive development I have to disable re-frame-10x in the `project.clj`, which is a shame because it's great (and useful for that work - moving forward and backwards between states).

Also, re-frame-10x doesn't fully slide into view when using these views.

![image](https://user-images.githubusercontent.com/3037019/44159839-86bcab80-a0b0-11e8-85ae-e6124c5cc87a.png)
In the image above, you can see that re-frame-10x is only showing some of the panel, because otherwise it would cover the entire page.

![image](https://user-images.githubusercontent.com/3037019/44159855-920fd700-a0b0-11e8-99b1-e3ee317b45aa.png)
In this image, you can see how re-frame-10x has prevented the CSS from displaying full-width (the grey background should go all the way across).

**Comment by danielcompton** [comment] 2019-02-03 22:31
Hey, I'm happy to take patches to improve this further, or even a reproducing case to begin with. I can't reproduce this on todomvc (I know, not the best example). Day8 mainly works on desktop apps so I don't have a mobile project setup to test this further.

<img width="380" alt="screenshot of google chrome 4-02-19 11-29-05 am" src="https://user-images.githubusercontent.com/811954/52183775-44f70b80-2870-11e9-834a-c57a915cb178.png">
<img width="368" alt="screenshot of google chrome 4-02-19 11-29-12 am" src="https://user-images.githubusercontent.com/811954/52183776-46283880-2870-11e9-9793-1431fb2fe49c.png">

**Comment by kimo-k** [comment] 2023-07-27 20:57
Hey, it's been a while. Sorry to hear your layout got messed up. I do wonder if there's a naming conflict in the css, since 10x uses re-com, which uses bootstrap classes. We're actually hoping to overhaul re-com's css, so this may improve eventually.

Otherwise, I can't reproduce the layout bug either. 

I know our mobile support isn't great, but it seems out of scope. A popout window should be the right choice for testing responsive layouts in the mobile simulator.

**Closed by kimo-k** 2023-07-27 20:57 UTC
Labels: needs info, can't reproduce
