### ISSUE TITLE
Deps: Breaks with React/React-dom 17.0.0+

### ISSUE THREAD

**Issue by unonull** [day8/re-frame-10x#289] opened 2020-12-23 18:35 UTC
Re-frame 10x breaks with React/React-dom `17.0.0`+ -- Reagent `1.0.0` now uses `17.0.0`+ as the default

**Comment by lucywang000** [comment] 2021-02-14 13:41
Could you paste the error message and/or stack trace here?

**Comment by superstructor** [comment] 2021-02-16 00:52
Duplicate of #275

**Closed by superstructor** 2021-02-16 00:52 UTC
